services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./volumes/qdrant:/qdrant/storage

    postgres:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: log_db
      ports: # Questa sezione è l'unica aggiunta/modifica
        - "5432:5432" # Mappa la porta 5432 del container alla porta 5432 del tuo host
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=log_db
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=tiziano
      - N8N_BASIC_AUTH_PASSWORD=toor
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  mcp-node:
    image: node:18-slim
    working_dir: /workspace
    volumes:
      - .:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]

  mcp-py:
    image: python:3.10-slim
    working_dir: /workspace
    volumes:
      - .:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  n8n_data: